### ISSUE TITLE
Manage Recycle Views

### ISSUE THREAD

**Issue by SFr682k** [InformatikMWG/mwg-organizer#1]
Currently, dummy content gets inserted into the Recycle view of the Vertretungsplan fragment.  
These three tasks have to be fulfilled:

1. Find a way of adding items
2. Find a way of removing items
3. Make the items clickable and execute an action when they are clicked
4. Determine which item has been clicked

**Comment by Dudeldu** [comment]
Items are clickable now and a task can be executed depending on wich item
