### ISSUE TITLE
Open PDF files, Pt. I

### ISSUE THREAD

**Issue by SFr682k** [InformatikMWG/mwg-organizer#7]
The `openPDF` method inside the `FileSelectionListContent` class should create an array containing the file paths and labels:

    String[][] pdffiles = new String[<total number of files/buttons in list>][2]
    
    // Array befüllen     [x][0]: Dateilabel
    //                    [x][1]: Dateipfad

The value *x* of the file selected should be stored in an `int` variable:

    int currentFilePos = x;

Currently I'm not that familiar with `DisplayPDF`'s code. I'll try to look at it as soon as possible.

**Comment by Dudeldu** [comment]
its working now
